import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#D8D8D8',
    marginTop: 5,
  },
  container1: {
    //flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#D8D8D8',
    marginTop: 5,
  },

  button: {
    backgroundColor: '#0782F9',
    width: '60%',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
  },
  buttonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16,
  },
  center: {
    alignItems: 'center',
  },
  heading: {
    marginTop: 10,
    marginVertical: 5,
    fontSize: 30,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    color: 'black',
  },
  inpcont: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
  },
  input: {
    flex: 1,
    //marginTop: 10,
    fontSize: 20,
    backgroundColor: 'white',
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 50,
    shadowColor: 'black',
    elevation: 13,
  },
  button: {
    //marginTop: 40,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 50,
    backgroundColor: 'black',
  },
  button_Add: {
    marginTop: 10,
    marginBottom: 5,
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 100,
    backgroundColor: 'black',
  },
  buttontxt: {
    fontSize: 25,
    fontWeight: 'bold',
    color: 'white',
  },
  small: {
    marginVertical: 20,
    fontSize: 20,
    fontWeight: 'bold',
  },
  todo: {
    //flexDirection: 'row',
    //marginHorizontal: 10,
    elevation: 20,
    shadowColor: 'black',
    backgroundColor: '#FFFF',
    paddingHorizontal: 10,
    paddingVertical: 10,
    //marginHorizontal: 50,
    marginBottom: 20,
    borderRadius: 20,
    height: 110,
    width: 370,
  },

  note: {
    //flexDirection: 'row',
    //marginHorizontal: 10,
    elevation: 20,
    shadowColor: 'black',
    backgroundColor: '#FFFF',
    paddingHorizontal: 10,
    paddingVertical: 10,
    //marginHorizontal: 50,
    marginBottom: 20,
    borderRadius: 20,
    height: 250,
    width: 370,
  },
  todo321: {
    //flexDirection: 'row',
    //marginHorizontal: 10,
    elevation: 20,
    shadowColor: 'black',
    backgroundColor: 'white',
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 5,
    borderRadius: 20,
    height: 250,
    width: 370,
  },
  note321: {
    elevation: 20,
    shadowColor: 'black',
    backgroundColor: 'white',
    paddingHorizontal: 10,
    paddingVertical: 10,
    //marginHorizontal: 50,
    marginBottom: 5,
    borderRadius: 20,
    height: 250,
    width: 370,
  },

  txt: {
    flex: 1,
    fontSize: 18,
    paddingVertical: 5,
    //marginHorizontal: 120,
    paddingHorizontal: 10,
    color: 'black',
  },
  txt321: {
    flex: 1,
    fontSize: 18,
    paddingVertical: 5,
    //marginHorizontal: 120,
    paddingHorizontal: 10,
    color: 'red',
    fontWeight: 'bold',
  },
  button_txt: {
    flex: 1,
    fontSize: 18,
    paddingVertical: 5,
    paddingHorizontal: 5,
    color: 'black',
    fontWeight: 'bold',
  },
  button_txt2: {
    flexDirection: 'row',
    fontSize: 18,
    paddingVertical: 5,
    paddingHorizontal: 30,
    marginLeft: 5,
    color: 'red',
    fontWeight: 'bold',

    color: 'black',
  },
  inp: {
    //flex: 1,
    width: 350,
    fontSize: 18,
    borderColor: 'grey',
    marginTop: 10,
    borderRadius: 50,
    borderWidth: 1,
  },
  inp321: {
    //flex: 1,
    width: 350,
    fontSize: 18,
    borderColor: 'grey',
    //marginTop: 10,
    borderRadius: 20,
    borderWidth: 1,
  },
  icon: {
    paddingLeft: 10,
    paddingRight: 10,
  },
  scrollView: {
    backgroundColor: '#D8D8D8',
    marginHorizontal: 20,
    marginTop: 10,
    marginHorizontal: 10,
  },
  // scrollView_N: {
  //   backgroundColor: '#D8D8D8',
  //   marginHorizontal: 20,
  //   marginTop: 10,
  //   marginHorizontal: 10,
  // },
  text: {
    fontSize: 42,
  },
  todo1: {
    //alignItems: 'center',
    flexDirection: 'row',
    //marginHorizontal: 10,
    elevation: 20,
    shadowColor: 'black',
    backgroundColor: '#DCDCDC',
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 5,
    marginHorizontal: 25,
    borderRadius: 50,
    height: 50,
    width: 300,
  },
  tray: {
    //alignItems: 'center',
    flexDirection: 'row-reverse',
    //marginHorizontal: 10,
    //elevation: 20,
    //shadowColor: 'black',
    //backgroundColor: '#DCDCDC',
    //paddingHorizontal: 20,
    //paddingVertical: 10,
    //marginBottom: 5,
    //marginHorizontal: 25,
    //borderRadius: 50,
    //height: 50,
    //width: 300,
  },
  note1: {
    //alignItems: 'center',
    flexDirection: 'row',
    //marginHorizontal: 10,
    elevation: 20,
    shadowColor: 'black',
    backgroundColor: '#DCDCDC',
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginTop: 100,
    marginBottom: 5,
    //marginHorizontal: 25,
    marginLeft: 80,
    borderRadius: 50,
    height: 50,
    width: 160,
  },
  buttonView: {
    margin: 10,
  },

  centeredView: {
    flex: 1,
    //justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    backgroundColor: '#000000aa',
  },

  modalView: {
    //flex: 0.5,
    margin: 50,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 10,
    width: 350,
    //height: 1000,
    //alignItems: 'center',
    shadowColor: '#000',
    // shadowOffset: {
    //   width: 10,
    //   height: 50,
    // },
    // shadowOpacity: 0.25,
    // shadowRadius: 4,
    // elevation: 5,
  },

  modalView1: {
    margin: 50,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 10,
    width: 250,
    shadowColor: '#000',
  },

  inp1: {
    //flex: 1,
    width: 330,
    padding: 10,
    height: 50,
    fontSize: 15,
    borderColor: 'grey',
    marginTop: 10,
    borderRadius: 50,
    borderWidth: 1,
  },

  button123: {
    width: 150,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    padding: 10,
    marginLeft: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  dropdown: {
    height: 50,
    borderColor: 'gray',
    borderWidth: 0.5,
    borderRadius: 50,
    paddingHorizontal: 8,
  },
  custom_button: {
    height: 35,
    width: 35,
    marginRight: 10,
    marginBottom: 10,
    alignSelf: 'center',
  },
  display: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  btn: {
    flexDirection: 'row',
    padding: 5,
    //margin: 10,
  },

  container_cat: {
    flex: 1,
  },
  headerText: {
    color: 'black',
  },
});

export default styles;
